### ISSUE TITLE
"for" snippet description 

### ISSUE THREAD

**Issue by mrfz** [vitalyruhl/intouch-language#16]
Hello, Vitaly. 
I think that I found little mistyping in the description of for-loop snippet. Now its:
https://github.com/vitalyruhl/intouch-language/blob/ed8701520c5381124af0395e77ea5f41da6c890f/snippets/vbi.json#L43-L54

and must be: 
`    "description": "for-next-block"`

**Comment by vitalyruhl** [comment]
thx
